kind: pipeline
name: default

steps:
  - name: install
    image: ruby
    volumes:
      - name: bundle
        path: /usr/local/bundle
    commands:
      - bundle install --jobs=3 --retry=3

  - name: test
    image: ruby
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
      CI: true
    volumes:
      - name: bundle
        path: /usr/local/bundle
    commands:
      - rake
  - name: build_gem
    image: ruby
    environment:
      RUBYGEMS_KEY:
        from_secret: RUBYGEMS_KEY
    volumes:
      - name: bundle
        path: /usr/local/bundle
    commands:
      - gem signin --code $RUBYGEMS_KEY
      - gem build instance_store.gemspec
      - gem push
    when:
      branch:
      - release
      event:
        pull_request: merged

volumes:
  - name: bundle
    temp: {}
